config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup'
  }

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }

  # nested routes comment can only be created when a event is created
  resources :events do
    resources :comments
  end

  resources :users, :only =>[:show]
  get "/users/:id/events", to: "users#show_user_events", as:"show_user_events"



  post '/events/:id/join', to: 'events#join', as: 'join_event'

  get '/aboutus', to: 'static_pages#aboutus'

  root 'static_pages#home'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :message, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]

  def create
    @comment = @event.comments.create(params[:comment].permit(:message))
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      redirect_to event_path(@event)
    else
      flash[:error] = 'Comment cannot be blank!'
      redirect_to event_path(@event)
    end
  end

  def destroy
    @comment.destroy
    redirect_to event_path(@event)
  end

  def edit

  end

  def update
    if @comment.update(params[:comment].permit(:message))
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = 'You shall not pass!'
      redirect_to @event
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="hold-eventform-container">


<% render 'comments/form' %>

<% @comments.each do |comment| %>

  <div class="commentbox">
    <div class="comment-avatar">
            <img src="http://www.gravatar.com/avatar">
          </div>
    <%= comment.message %><br/>
      <p>By <span class="maroon"><%= comment.user.name %></span></p>
  </div>
      <br/>

<div class="hold-comment-buttons">
  <% if current_user == comment.user%>
  <%= link_to 'Delete', [comment.event, comment], method: :delete, :class => 'btn-delete-comment' %>
  <%= link_to 'Edit', edit_event_comment_path(comment.event, comment), :class => 'btn-edit-comment' %>
  <% end %>
</div>
<% end %>

</div>

<br/><br/>

app/views/comments/_form.html.erb
<section class="section-standard">
    <h1>
        Comments
    </h1>

    <div class="hold-eventform-container">

        <p style="text-align:center;">Total:
            <%= pluralize(@comments.count, 'Comment') %></p>
        <br/><br/>
        <!-- <%= pluralize(@comments.count, 'Comment')%> -->

        <%= form_for ([@event, @event.comments.build]) do |f| %>
          <!-- <% if @event.errors.any? %>
            <%= message %>
          <% end %> -->
          <%= f.text_area :message %>
          <%= f.submit 'Post', :class => 'comment-submit' %>

        <% end %>

    </div>

</section>

app/views/comments/edit.html.erb
<section class="section-standard">

  <h1> Edit Comment </h1>

<%= form_for ([@event, @comment]) do |f| %>
  <%= f.text_area :message %>
  <%= f.submit 'Update', :class => 'comment-submit' %>

<% end %>

</section>