config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup'
  }

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }

  # nested routes comment can only be created when a event is created
  resources :events do
    resources :comments
  end

  resources :users, :only =>[:show]
  get "/users/:id/events", to: "users#show_user_events", as:"show_user_events"



  post '/events/:id/join', to: 'events#join', as: 'join_event'

  get '/aboutus', to: 'static_pages#aboutus'

  root 'static_pages#home'

end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :picture, PictureUploader
  # geocoded_by :event_address
  geocoded_by :address_country

  def address_country
    [self.event_address].to_s + ' Singapore'
  end
  # , :lookup => :region == "SG"
  # def event_address
  #    Venue.near( params["event_address"] << ", Singapore" , 50)
  # end
  # Geocoder.search('event_address', :params => {:country => "sg"})

  #   def event_address
  #     "#{locale}, Singapore"
  #   end

  # geocoded_by :event_address do |prof,results|
  #   if result = results.select{|res| res.country_code == "SG" }.first
  #     unless (result.latitude.nil? || result.longitude.nil?)
  #       prof.latitude = result.latitude
  #       prof.longitude = result.longitude
  #     end
  #     result.coordinates
  #   end
  # end
  after_validation :geocode

  has_and_belongs_to_many :users

  has_many :comments, dependent: :destroy
  belongs_to :creator, class_name: 'User', primary_key: 'id'

  validates :event_name, presence: true, length: { maximum: 20, message: "Please input less than 20 letters" }
  validates :event_address, presence: true
  validates :details, presence: true, length: { maximum: 50, message: "Please input less than 50 letters" }
  validates :postal_code, presence: true, length: { is: 6, message: "Please give a valid postal code" }, numericality: { only_integer: true, message: "Numbers only" }
  validates :players_req, presence: true
  validate :check_time

  private

  def check_time
    return unless start_time and end_time
    errors.add(:start_time, "must be before end time") unless start_time < end_time
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update, :join]

  def index
    # @events = Event.all
    # settings for dev mode
    # @events = Event.where(["sports_cat LIKE ? or event_name LIKE ? or event_address LIKE ? or details LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%"])
    # Settings for production mode
    @events = Event.where(["sports_cat ILIKE ? or event_name ILIKE ? or event_address ILIKE ? or details ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%"])

    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      event_path = view_context.link_to event.event_name, event_path(event)
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow "<b>#{event_path}</b>"
    end
  end



  def show
    @event = Event.find(params[:id])
    # @event.event_date = @events.event_date.strftime("%d/%m/%Y")
    @eventusers = Event.find(params[:id]).users
    @comments = Comment.where(event_id: @event).order('created_at DESC')
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow event.event_name
    end
  end

  def new
    @event = Event.new
  end

  def create

    current_user
    # @event = Event.new(event_param)
    @event = current_user.events.new(event_params)
    @event.creator_id = current_user.id

    respond_to do |format|
      if @event.save

        CreateMailer.event_created(current_user).deliver
        format.html { redirect_to @event, notice: 'You have added a new event.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event =Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Your event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user
    @event = Event.find(params[:id])
    # @user = User.find(params[:id])
    @eventusers = @event.users

    CancelMailer.cancel_event(@eventusers, @event).deliver

    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_path, notice: 'You have successfully deleted your event' }
      format.json { head :no_content }
    end
  end

  def join
    current_user
    @user = current_user
    @event = Event.find(params[:id])
    # if @user.events.includes(:events).where('id') != @event
    # if Post.includes(:author).where(..)
    # User.joins(:events).where("@user.events ")
    # user3.events.where(id: '4')
    if @user.events.where(id: @event).exists? || @event.users.size >= @event.players_req
      # debugger
      flash[:notice] = 'Oops, you have already joined this event.'
      redirect_to event_path
    else
      @user.events << @event
      JoinMailer.join_event(current_user, @event).deliver
      flash[:notice] = 'You have joined the event.'
      redirect_to event_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_date, :start_time, :end_time, :event_address, :postal_code, :players_req, :sports_cat, :event_name, :details, :picture, :creator_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :'Event' %>
    <%= f.text_field :event_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :'Sports Category' %>
    <div class="form-inline">
      <%= f.select(:sports_cat, options_for_select([['Football', 'Football'], ['Basketball', 'Basketball'], ['Badminton', 'Badminton'], ['Tennis', 'Tennis'], ['Bowling', 'Bowling'], ['Hockey', 'Hockey'], ['Others', 'Others']]), {}, {class: "form-control"}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :'Date' %>
    <div class="input-group date">
      <!-- <%= f.select(:event_date, options_for_select(2016..2020), {}, {class: "form-control"}) %> -->
      <!-- <%= f.select(:event_date, options_for_select([['Jan', 'Jan'], ['Feb', 'Feb'], ['Mar', ''], ['Apr', 'Apr'], ['May', 'May'], ['Jun', 'Jun'], ['Jul', 'Jul'], ['Aug', 'Aug'], ['Sep', 'Sep'], ['Oct', 'Oct'], ['Nov', 'Nov'], ['Dec', 'Dec']]), {}, {class: "form-control"}) %> -->
      <!-- <%= f.select :event_date, (1..31).map { |i| "%02d" % i }, {}, {class: "form-control"} %> -->
      <%= f.text_field :event_date, class: "form-control" %>
      <div class="input-group-addon">
        <span class="glyphicon glyphicon-th"></span>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :'Start Time'%>
    <div class="form-inline input-group bootstrap-timepicker timepicker">
      <!-- <%= f.select :start_time, (0..12).map { |i| "%02d" % i }, {}, {class: "form-control"} %> -->
      <!-- <%= f.select :start_time, (0..59).map { |i| "%02d" % i }, {}, {class: "form-control"} %> -->
      <!-- <%= f.select :start_time, options_for_select([['AM', 'AM'], ['PM', 'PM']]), {}, {class: "form-control"} %> -->
      <%= f.text_field :start_time, class: "form-control input-small", id: "timepicker1" %>
      <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :'End Time' %>
    <div class="form-inline input-group bootstrap-timepicker timepicker">
      <!-- <%= f.select :end_time, (0..59).map { |i| "%02d" % i }, {}, {class: "form-control"} %> -->
      <!-- <%= f.select :end_time, options_for_select([['AM', 'AM'], ['PM', 'PM']]), {}, {class: "form-control"} %> -->
      <%= f.text_field :end_time, class: "form-control input-small", id: "timepicker2" %>
      <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :'Location' %>
    <%= f.text_field :event_address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :'Postal Code' %>
    <%= f.text_field :postal_code, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :'Players Required' %>
    <div class="form-inline">
      <%= f.number_field :players_req, min: 2, max: 50, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :'Details' %>
    <%= f.text_area :details, class: "form-control", rows: "3" %>
  </div>
  <div class="form-group">
    <%= f.label :'Upload event photograph' %>
    <%= f.file_field :picture, autofocus: true %>
  </div>
  <div>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>Edit Event</h1>
      <%= render 'form', event: @event %>
      <%= link_to 'Back', events_path %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyD0Y2-I3ZG8u77WjYagSJd5q5wIaD_aQSk"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  <section id="all-events" class="section-standard">
    <h1> <span class="maroon">Events</span> Available </h1>

    <div class="container">
      <%= form_tag events_path, :method => 'get', class: "search-form search-wrapper" do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
        <button><%= submit_tag "Search" %><i class="fa fa-search"></i></button>
      <% end %>

    </div>


  <%= react_component 'Events', { events: @events } %>

  <!-- map -->
  <section class="section-standard">
    <div class="allEventsMap" style='width: 100%;'>
      <h1>Find <span class="maroon">your events</span></h1>
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>

</section>



</section>

<script type="text/javascript">

// $(document).on('turbolinks:load', named_function );
// var named_function = function() {
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(12);
    });
  // };
</script>
<!-- map -->

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>New Event</h1>
      <%= render 'form', event: @event %>
      <%= link_to 'Back', events_path %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%= render 'partials/herointro' %>
<script src="//maps.google.com/maps/api/js?key=AIzaSyD0Y2-I3ZG8u77WjYagSJd5q5wIaD_aQSk"></script>

<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<br/><br/>

<%= react_component 'Event', {event: @event, eventusers: @eventusers}, {joinpath: join_event_path} %>
<!-- equivalent to -->
<!-- link_to "Join", { controller: "events", action: :join }, method: :post -->

<div style="clear:both;"></div>



<!-- <%= flash[:notice] %> -->

<!-- map -->
<div>
<!-- Latitude is <%=@event.latitude%>
Longitude is <%=@event.longitude%> -->
</div>


<div id="eventMap" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">

        <h4 class="modal-title">Location</h4>

      </div>
      <div class="modal-body">
        <div>
          <div id="map" style='width: 100%; height: 600px;'></div>
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
$('#eventMap').on('shown.bs.modal', function(e){
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {region: 'sg'}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15);
  });
});
</script>
<!-- map -->

<div id="scroller-anchor"></div>
<div class="players-list" id="scroller">
  <div class="players-list-hold">
  <h5><%=@eventusers.length %> players have joined!</h5>
    <ul>
        <li>
            <% @eventusers.each do |eventuser| %>
            <a href="#"><%=link_to eventuser.name, user_path(eventuser) %></a>
            <!-- <%= eventuser.email %><br>
            <%= eventuser.contact_number %><br> -->
              <%end%>
        </li>
    </ul>
  </div>
  </div>





<div style='clear:both;'></div>

<hr/>

<%= render 'comments/form' %>

<%= render 'comments/comment' %>